name: Deploy to ECR

on:
  workflow_run:
    workflows: [Deploy IaC]
    types:
      - completed

jobs:
  
  build:
    
    name: Build Image
    runs-on: ubuntu-latest   
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_TERRAFORM }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_TERRAFORM }}
        aws-region: us-east-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1


    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: fs000-images_repository
        IMAGE_TAG: latest
      uses: isbang/compose-action@v1.2.0
      with:
        compose-file: ./docker/app/docker-compose.yml
        services: |
          app
          nginx
    #   run: 
    #     docker push $ECR_REGISTRY/file_submission_input:$IMAGE_TAG
