name: Deploy IaC

on:
  push:
    branches: [master]
         

jobs:
  deploy:
    name: Deploy IaC
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2

      - name: Configure AWS credentials
        uses: aws-action/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_TERRAFORM }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_TERRAFORM }}
          aws-region: us-east-2
#################################

      - name: Terraform - IaC Apply
        env:
          COMMAND_IAC: terraform
        run: |
          cd IaC
          $COMMAND_IAC init
          $COMMAND_IAC validate
          $COMMAND_IAC plan
          $COMMAND_IAC apply -auto-approve

      # - uses: actions/checkout@v2

      # - uses: isbang/compose-action@v1.2.0
      #   with:
      #     compose-file: ./docker/app/docker-compose.yml
      #     services: |
      #       app
      #       nginx
      #   env:
      #     AWS_REGION: us-east-2                   # set this to your preferred AWS region, e.g. us-west-1
      #     ECR_REPOSITORY: fs000-images_repository     # set this to your Amazon ECR repository name
      #     CONTAINER_NAME: file_submission_input  
      #   run:
      #     docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
  